{% set build = 0 %}
{% set version = "1.20190621" %}

package:
  name: vcsh
  version: {{ version }}

source:
  url: https://github.com/RichiH/vcsh/archive/v{{ version }}.tar.gz
  sha256: e7c108f98da16e5ec5ae41692552aff31ee02d7d8849e6bf6efdfa68ed697204
  patches:
    - Makefile.patch

build:
  number: {{ build }}
  noarch: generic
  script:
    - make install

requirements:
  build:
    - git
    - make
  run:
    - git

test:
  commands:
    - vcsh -h

about:
  home: https://github.com/RichiH/vcsh
  license: GPL-2.0
  license_file: LICENSE
  summary: config manager based on Git

extra:
  recipe-maintainers:
    - lebedov
