{% set build = 0 %}
{% set version = "1.20190621-1" %}

package:
  name: vcsh
  version: {{ version }}

source:
  url: https://github.com/RichiH/vcsh/archive/v{{ version }}.tar.gz
  sha256: d745ae6267347a3f39a9540bde7fc08d6fe38f477932c3e87a264e60cf99f784
  patches:
    - Makefile.patch

build:
  number: {{ build }}
  noarch: generic
  script:
    - make install

requirements:
  build:
    - git
    - make
  run:
    - git

test:
  commands:
    - vcsh -h

about:
  home: https://github.com/RichiH/vcsh
  license: GPL-2.0
  license_file: LICENSE
  summary: config manager based on Git

extra:
  recipe-maintainers:
    - lebedov
