{% set build = 0 %}
{% set version = "2.0.6" %}

package:
  name: vcsh
  version: {{ version }}

source:
  url: https://github.com/RichiH/vcsh/archive/v{{ version }}.tar.gz
  sha256: 5c0c12abad19334afca668fe716ff4c41e7ed257b9bf2a6faa97b85f0f82ceea
  patches:
    - Makefile.patch

build:
  number: {{ build }}
  noarch: generic
  script:
    - make install

requirements:
  build:
    - git
    - make
  run:
    - git

test:
  commands:
    - vcsh -h

about:
  home: https://github.com/RichiH/vcsh
  license: GPL-2.0-or-later
  license_file: LICENSE
  summary: config manager based on Git

extra:
  recipe-maintainers:
    - lebedov
