{% set build = 0 %}
{% set version = "2.0.5" %}

package:
  name: vcsh
  version: {{ version }}

source:
  url: https://github.com/RichiH/vcsh/archive/v{{ version }}.tar.gz
  sha256: 4134b06d1bd37e13a280456547fba2a58ee05bb2c4c447b3523b77dc61b0d982
  patches:
    - Makefile.patch

build:
  number: {{ build }}
  noarch: generic
  script:
    - make install

requirements:
  build:
    - git
    - make
  run:
    - git

test:
  commands:
    - vcsh -h

about:
  home: https://github.com/RichiH/vcsh
  license: GPL-2.0-or-later
  license_file: LICENSE
  summary: config manager based on Git

extra:
  recipe-maintainers:
    - lebedov
