travis:
  secure:
    BINSTAR_TOKEN: L4y9yAVXANiZSAjGTs90FgJB1vkp3t/wTUh2a0M23SNoE8/uud6nOn8iLXSkzyqkiAGwsFyH1kFNr/i/hIsrAY0NU9nAYn25FtcU/Q+vjWvGH0tZOVwQO651UUEmlCyJSduuuX4RFqknyADePGoW1z2oEIUbeShWfXm1J51r11FLE8TtQtBWHsLf4MTG+AXXjJntiBn7v8ben0d37vkhFM4KdyH220ZhEao22VXEbUm5aMMElmH7nhhsrakR0jTnhpG9+B0F1u0wPzQkBB7D3XnuUTDLct1nExeR6aBI+H63ZEaBSu7QohYrHluSKHpg7ZSontDOZxikYuIJA6LCgMVTm1UUMLQYIu5nAY03TfPt7z3vFtfrYaGN+wXsbfZOfzGaZXPuUTwULHbCqCb51BYUpqEFAr+hXBZ1DNunGaL8ny8HhsNulIYzPBLJRTn35W4F5pZ0LY3nm2smBZZs9EKdqvoHo69gmLM/T+KWydER9QY6IdUoaq/zttTHRTdeg7q+JBeJbpFhNZriiyjWGsE8u07Wi8SPfMH2v7FlAOmcSfbTJuz46uqeXZDkA//NZ3dMeZnECtp05raBH1UPsFbLe/y+XWaBsSA8hvFvht7A+65E1aIotCNh0Zy71d5xeoE1rkMPP5zDt+moMCJ9Vz7PQe2BMuwGVHS2PlLcXBk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
